# Generated by Django 5.0.2 on 2024-03-03 12:05

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fitbit_access_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='access token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitbit_expiration_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitbit_getmeas_data',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='getmeas data'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitbit_refresh_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='refresh token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitbit_scope',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='scope'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitbit_token_type',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='token_type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitbit_userid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='user id'),
        ),
    ]
