# Generated by Django 5.0.2 on 2024-02-13 10:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_birthday_profile_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='توکن دسترسی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='توکن بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scope',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='سطح دسترسی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_type',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='نوع توکن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='آیدی کاربر'),
        ),
    ]
