# Generated by Django 5.0.2 on 2024-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='getmeas_data',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='getmeas data'),
        ),
    ]
